name: saver_expense_manager
description: App to manage expenses
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_localizations: ^1.13.0
  firebase_ui_oauth: ^1.6.0
  firebase_ui_oauth_google: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  rive: ^0.13.20
  syncfusion_flutter_charts: ^28.1.38
  syncfusion_flutter_core: ^28.1.39

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf


  assets:
    - assets/animations/
    - assets/images/
