name: saver_expense_manager
description: App to manage expenses
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.4
  equatable: ^2.0.7
  file_picker: ^9.0.0
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  firebase_storage: ^12.4.3
  firebase_ui_auth: ^1.16.1
  firebase_ui_localizations: ^1.13.1
  firebase_ui_oauth: ^1.6.1
  firebase_ui_oauth_google: ^1.4.1
  firebase_ui_storage: ^2.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.19.0
  mat_month_picker_dialog: ^1.1.2
  mime: ^2.0.0
  shared_preferences: ^2.5.2
  syncfusion_flutter_charts: ^28.2.6
  syncfusion_flutter_core: ^28.2.6
  user_api:
    path: packages/user_api
  user_api_remote:
    path: packages/user_api_remote
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter_icons:
  image_path: "assets/images/logo.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 23
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

  assets:
    - .env
    - assets/animations/
    - assets/images/
