name: saver_expense_manager
description: App to manage expenses
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: ">=3.47.0"

dependencies:
  bloc: ^9.2.1
  cloud_firestore: ^6.8.0
  country_flags: ^4.1.2
  cunning_document_scanner: ^3.0.1
  dio: ^5.11.0
  equatable: ^2.1.0
  file_picker: ^12.0.0
  firebase_analytics: ^12.4.6
  firebase_app_check: ^0.4.6
  firebase_auth: ^6.5.7
  firebase_core: ^4.13.0
  firebase_crashlytics: ^5.2.7
  firebase_performance: ^0.11.4+2
  firebase_remote_config: ^6.5.6
  firebase_storage: ^13.4.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.12
  gemini_nano_android: ^1.2.0
  get_it: ^9.2.1
  go_router: ^18.0.0
  google_sign_in: ^7.2.0
  hugeicons: ^1.1.7
  intl: ^0.20.3
  material_ui: ^1.0.0
  mime: ^2.0.0
  open_file: ^4.0.0
  package_info_plus: ^10.2.1
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  syncfusion_flutter_charts: ^34.2.4
  syncfusion_flutter_core: ^34.2.4
  uuid: ^4.6.0

dev_dependencies:
  bloc_test: ^10.0.0
  fake_cloud_firestore: ^4.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  network_image_mock: ^2.1.1
  path_provider_platform_interface: ^2.1.3
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.3.0

flutter_launcher_icons:
  android: true
  image_path_android: "assets/images/app-main-logo-rounded.png"
  adaptive_icon_background: "#2C6C41"
  adaptive_icon_foreground: "assets/images/app-main-logo-rounded.png"
  ios: true
  image_path_ios: "assets/images/app-main-logo-rounded.png"
  remove_alpha_ios: true
  background_color_ios: "#2C6C41"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/fonts/
    - assets/logos/
    - .env

  fonts:
    - family: GoogleSansFlex
      fonts:
        - asset: assets/fonts/GoogleSansFlex-VariableFont.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-VariableFont.ttf
        - asset: assets/fonts/Merriweather-Italic-VariableFont.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont.ttf
          style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont.ttf
        - asset: assets/fonts/Nunito-Italic-VariableFont.ttf
          style: italic
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont.ttf
        - asset: assets/fonts/OpenSans-Italic-VariableFont.ttf
          style: italic
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont.ttf
          style: italic
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-VariableFont.ttf
        - asset: assets/fonts/SourceCodePro-Italic-VariableFont.ttf
          style: italic
