// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr0Q9aOOiIOra_Jkown14_Omv8v0rlWpo',
    appId: '1:269318126118:android:19c0edc290b70b9dfb04e7',
    messagingSenderId: '269318126118',
    projectId: 'saver-expense-manager',
    storageBucket: 'saver-expense-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCliGUV5JtQkDDsIqFK_SXW9HzUzI8S63Y',
    appId: '1:269318126118:ios:ccccf972db5c7042fb04e7',
    messagingSenderId: '269318126118',
    projectId: 'saver-expense-manager',
    storageBucket: 'saver-expense-manager.firebasestorage.app',
    androidClientId:
        '269318126118-59i8g260ddou15dolopo2thrjc0tj6r2.apps.googleusercontent.com',
    iosClientId:
        '269318126118-7t1rqm8oho4m39a01tlvavd8735559dn.apps.googleusercontent.com',
    iosBundleId: 'com.pmorales.saver.expense.manager',
  );

  static const String googleClientId =
      '269318126118-54eh6vkdnfggcl9jv43ds7pcd927gd34.apps.googleusercontent.'
      'com';

  static const String googleRedirectUri =
      'https://saver-expense-manager.firebaseapp.com/__/auth/handler';
}
