// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAcoroTvz0_YXTx-b9oKUbEmKyrjXKRcw',
    appId: '1:269318126118:android:09311aaa03c92bdcfb04e7',
    messagingSenderId: '269318126118',
    projectId: 'saver-expense-manager',
    storageBucket: 'saver-expense-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjHJTHg_QH6D3Jd0EXdaU7_a8Wunijksg',
    appId: '1:269318126118:ios:e540158656abbe49fb04e7',
    messagingSenderId: '269318126118',
    projectId: 'saver-expense-manager',
    storageBucket: 'saver-expense-manager.firebasestorage.app',
    androidClientId:
        '269318126118-cp3js8sb2v0961q8mg3c6h4gtq22pmml.apps.googleusercontent.com',
    iosClientId:
        '269318126118-1okee6h2hvj2gft9p05ki94qisfatf89.apps.googleusercontent.com',
    iosBundleId: 'com.pmorales.saver.expense.manager',
  );

  static const String googleClientId =
      '269318126118-54eh6vkdnfggcl9jv43ds7pcd927gd34.apps.googleusercontent.'
      'com';

  static const String googleRedirectUri =
      'https://saver-expense-manager.firebaseapp.com/__/auth/handler';
}
