import 'package:user_api/user_api.dart';

List<ChartData> expensesChartData = <ChartData>[
  ChartData(
    category: Category(
      id: '1',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'TRANSPORT',
      icon: 'DIRECTIONS_CAR',
      color: '#FF64B5F6',
      type: CategoryType.expense,
    ),
    value: 15000.75,
  ),
  ChartData(
    category: Category(
      id: '2',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'FEEDING',
      icon: 'RESTAURANT',
      color: '#FFFFB74D',
      type: CategoryType.expense,
    ),
    value: 27500.50,
  ),
  ChartData(
    category: Category(
      id: '3',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'HEALTH',
      icon: 'LOCAL_HOSPITAL',
      color: '#FF81C784',
      type: CategoryType.expense,
    ),
    value: 13000.25,
  ),
  ChartData(
    category: Category(
      id: '4',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'ENTERTAINMENT',
      icon: 'MOVIE',
      color: '#FFBA68C8',
      type: CategoryType.expense,
    ),
    value: 12000.73,
  ),
  ChartData(
    category: Category(
      id: '5',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'TRIPS',
      icon: 'CARD_TRAVEL',
      color: '#FFFFF176',
      type: CategoryType.expense,
    ),
    value: 22000.13,
  ),
  ChartData(
    category: Category(
      id: '6',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'TECHNOLOGY',
      icon: 'COMPUTER',
      color: '#FF4DD0E1',
      type: CategoryType.expense,
    ),
    value: 18000.38,
  ),
  ChartData(
    category: Category(
      id: '7',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'EDUCATION',
      icon: 'SCHOOL',
      color: '#FFFF7043',
      type: CategoryType.expense,
    ),
    value: 19000.80,
  ),
  ChartData(
    category: Category(
      id: '8',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'FASHION',
      icon: 'CHECKROOM',
      color: '#FFF48FB1',
      type: CategoryType.expense,
    ),
    value: 14000.84,
  ),
  ChartData(
    category: Category(
      id: '9',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'TAXES',
      icon: 'PAYMENTS',
      color: '#FF8BC34A',
      type: CategoryType.expense,
    ),
    value: 30000.63,
  ),
  ChartData(
    category: Category(
      id: '10',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'INSURANCE',
      icon: 'SECURITY',
      color: '#FF2196F3',
      type: CategoryType.expense,
    ),
    value: 25000.35,
  ),
  ChartData(
    category: Category(
      id: '11',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'DWELLING',
      icon: 'HOUSE',
      color: '#FFA1887F',
      type: CategoryType.expense,
    ),
    value: 32000.40,
  ),
  ChartData(
    category: Category(
      id: '12',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'OTHERS',
      icon: 'CATEGORY',
      color: '#FFBDBDBD',
      type: CategoryType.expense,
    ),
    value: 5000.94,
  ),
];

List<ChartData> incomesChartData = <ChartData>[
  ChartData(
    category: Category(
      id: '1',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'SALARY',
      icon: 'ATTACH_MONEY',
      color: '#FF64B5F6',
      type: CategoryType.income,
    ),
    value: 52345.67,
  ),
  ChartData(
    category: Category(
      id: '2',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'BUSINESS',
      icon: 'BUSINESS',
      color: '#FFFFB74D',
      type: CategoryType.income,
    ),
    value: 41234.56,
  ),
  ChartData(
    category: Category(
      id: '3',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'FREELANCE',
      icon: 'PERSON_SEARCH',
      color: '#FF81C784',
      type: CategoryType.income,
    ),
    value: 37890.12,
  ),
  ChartData(
    category: Category(
      id: '4',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'RENTALS',
      icon: 'APARTMENT',
      color: '#FFBA68C8',
      type: CategoryType.income,
    ),
    value: 28901.34,
  ),
  ChartData(
    category: Category(
      id: '5',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'INVESTMENTS',
      icon: 'TRENDING_UP',
      color: '#FFFFF176',
      type: CategoryType.income,
    ),
    value: 15789.45,
  ),
  ChartData(
    category: Category(
      id: '6',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'INTERESTS',
      icon: 'PERCENT',
      color: '#FF4DD0E1',
      type: CategoryType.income,
    ),
    value: 10987.65,
  ),
  ChartData(
    category: Category(
      id: '7',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'PENSIONS',
      icon: 'CARD_MEMBERSHIP',
      color: '#FFFF7043',
      type: CategoryType.income,
    ),
    value: 8765.43,
  ),
  ChartData(
    category: Category(
      id: '8',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'DIVIDENDS',
      icon: 'MONETIZATION_ON',
      color: '#FFF48FB1',
      type: CategoryType.income,
    ),
    value: 7654.32,
  ),
  ChartData(
    category: Category(
      id: '9',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'GIFTS',
      icon: 'CARD_GIFTCARD',
      color: '#FF8BC34A',
      type: CategoryType.income,
    ),
    value: 6543.21,
  ),
  ChartData(
    category: Category(
      id: '10',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'REFUNDS',
      icon: 'RECEIPT_LONG',
      color: '#FF2196F3',
      type: CategoryType.income,
    ),
    value: 5432.10,
  ),
  ChartData(
    category: Category(
      id: '11',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'SALES',
      icon: 'LOCAL_OFFER',
      color: '#FFA1887F',
      type: CategoryType.income,
    ),
    value: 4321.09,
  ),
  ChartData(
    category: Category(
      id: '12',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      name: 'OTHERS',
      icon: 'CATEGORY',
      color: '#FFBDBDBD',
      type: CategoryType.income,
    ),
    value: 3210.98,
  ),
];

List<Category> expenseCategories = <Category>[
  Category(
    id: '1',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'TRANSPORT',
    icon: 'DIRECTIONS_CAR',
    color: '#FF64B5F6',
    type: CategoryType.expense,
  ),
  Category(
    id: '2',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'FEEDING',
    icon: 'RESTAURANT',
    color: '#FFFFB74D',
    type: CategoryType.expense,
  ),
  Category(
    id: '3',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'HEALTH',
    icon: 'LOCAL_HOSPITAL',
    color: '#FF81C784',
    type: CategoryType.expense,
  ),
  Category(
    id: '4',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'ENTERTAINMENT',
    icon: 'MOVIE',
    color: '#FFBA68C8',
    type: CategoryType.expense,
  ),
  Category(
    id: '5',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'TRIPS',
    icon: 'CARD_TRAVEL',
    color: '#FFFFF176',
    type: CategoryType.expense,
  ),
  Category(
    id: '6',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'TECHNOLOGY',
    icon: 'COMPUTER',
    color: '#FF4DD0E1',
    type: CategoryType.expense,
  ),
  Category(
    id: '7',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'EDUCATION',
    icon: 'SCHOOL',
    color: '#FFFF7043',
    type: CategoryType.expense,
  ),
  Category(
    id: '8',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'FASHION',
    icon: 'CHECKROOM',
    color: '#FFF48FB1',
    type: CategoryType.expense,
  ),
  Category(
    id: '9',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'TAXES',
    icon: 'PAYMENTS',
    color: '#FF8BC34A',
    type: CategoryType.expense,
  ),
  Category(
    id: '10',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'INSURANCE',
    icon: 'SECURITY',
    color: '#FF2196F3',
    type: CategoryType.expense,
  ),
  Category(
    id: '11',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'DWELLING',
    icon: 'HOUSE',
    color: '#FFA1887F',
    type: CategoryType.expense,
  ),
  Category(
    id: '12',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'OTHERS',
    icon: 'CATEGORY',
    color: '#FFBDBDBD',
    type: CategoryType.expense,
  ),
];

List<Category> incomeCategories = <Category>[
  Category(
    id: '1',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'SALARY',
    icon: 'ATTACH_MONEY',
    color: '#FF64B5F6',
    type: CategoryType.income,
  ),
  Category(
    id: '2',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'BUSINESS',
    icon: 'BUSINESS',
    color: '#FFFFB74D',
    type: CategoryType.income,
  ),
  Category(
    id: '3',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'FREELANCE',
    icon: 'PERSON_SEARCH',
    color: '#FF81C784',
    type: CategoryType.income,
  ),
  Category(
    id: '4',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'RENTALS',
    icon: 'APARTMENT',
    color: '#FFBA68C8',
    type: CategoryType.income,
  ),
  Category(
    id: '5',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'INVESTMENTS',
    icon: 'TRENDING_UP',
    color: '#FFFFF176',
    type: CategoryType.income,
  ),
  Category(
    id: '6',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'INTERESTS',
    icon: 'PERCENT',
    color: '#FF4DD0E1',
    type: CategoryType.income,
  ),
  Category(
    id: '7',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'PENSIONS',
    icon: 'CARD_MEMBERSHIP',
    color: '#FFFF7043',
    type: CategoryType.income,
  ),
  Category(
    id: '8',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'DIVIDENDS',
    icon: 'MONETIZATION_ON',
    color: '#FFF48FB1',
    type: CategoryType.income,
  ),
  Category(
    id: '9',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'GIFTS',
    icon: 'CARD_GIFTCARD',
    color: '#FF8BC34A',
    type: CategoryType.income,
  ),
  Category(
    id: '10',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'REFUNDS',
    icon: 'RECEIPT_LONG',
    color: '#FF2196F3',
    type: CategoryType.income,
  ),
  Category(
    id: '11',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'SALES',
    icon: 'LOCAL_OFFER',
    color: '#FFA1887F',
    type: CategoryType.income,
  ),
  Category(
    id: '12',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    name: 'OTHERS',
    icon: 'CATEGORY',
    color: '#FFBDBDBD',
    type: CategoryType.income,
  ),
];
